### ISSUE TITLE
Dockerfiles home path is hard coded

### ISSUE THREAD

**Issue by imesh** [abhishek0198/wso2dockerfiles-test-framework#15]
In the default configuration file, dockerfiles home path is hard coded to below:

      "dockerfileshome":"/Users/abhishektiwari/dev/dockerfiles"

IMO a such, user specific value should not be given in the default configuration file. It would be better to read this from an environment variable (DOCKERFILES_HOME) and if it's not available read it from the configuration file. The configuration file can keep this as blank since it's user specific.

**Comment by abhishek0198** [comment]
Fixed in commit
https://github.com/abhishek0198/wso2dockerfiles-test-framework/commit/9ee8d439f4890e7c4df483c08d865c855cb47d41

**Comment by chamilad** [comment]
This is not resolved. The commit doesn't fix this, instead reads the value only from the environment variable. Refer #22

**Comment by abhishek0198** [comment]
@chamilad I am confused here, should I use environment variable or config file for DOCKERFILES_HOME?

**Comment by chamilad** [comment]
The order should be config file -> if specified overridden from environment variable. If the values are to be constant most of the time, it will be a hassle to set environment variables everytime. What @imesh  has mentioned here is that it should not be only specified in the config file, in case it has to be changed everytime. This is the UX aspect of the project.

**Comment by abhishek0198** [comment]
@chamilad So the order is:
1. Read from config
2. If there is an env variable, it should override the value. 

Correct?

**Comment by imesh** [comment]
@abhishek0198 You may have misunderstood what I have mentioned above. 

As @chamilad has explained, please keep both options to read those parameters from, configuration file and environment variables while giving priority to environment variables. Thanks!

**Comment by abhishek0198** [comment]
Sure @imesh I will update the config reader accordingly. Thanks!
